### ISSUE TITLE
dynamic.h not found on ubuntu 16.04 lts

### ISSUE THREAD

**Issue by salesiss** [fredrikwidlund/libreactor#1]
libreactor builds fine on amazon ami linux, but not on ubuntu 16.04

Wich library is needed to apt-get install ?

Possibly is this the one ?
_http://libdynamic.readthedocs.io/en/latest/gettingstarted.html_

please confirm and possibly document it as requirement. tks!

root@ip-10-0-0-94:/mnt/ssd/libreactor/libreactor-master# make
make[1]: Entering directory '/mnt/ssd/libreactor/libreactor-master'
depbase=`echo src/reactor/reactor_pool.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ./libtool  --tag=CC   --mode=compile gcc -DPACKAGE_NAME=\"libreactor\" -DPACKAGE_TARNAME=\"libreactor\" -DPACKAGE_VERSION=\"1.0.0\" -DPACKAGE_STRING=\"libreactor\ 1.0.0\" -DPACKAGE_BUGREPORT=\"nospam@@gmail.com\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -I.    -std=gnu11 -g -O3 -flto -fuse-linker-plugin -I./src -Wall -Wextra -Wpedantic -MT src/reactor/reactor_pool.lo -MD -MP -MF $depbase.Tpo -c -o src/reactor/reactor_pool.lo src/reactor/reactor_pool.c &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DPACKAGE_NAME=\"libreactor\" -DPACKAGE_TARNAME=\"libreactor\" -DPACKAGE_VERSION=\"1.0.0\" "-DPACKAGE_STRING=\"libreactor 1.0.0\"" -DPACKAGE_BUGREPORT=\"great-job-man@gmail.com\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -I. -std=gnu11 -g -O3 -flto -fuse-linker-plugin -I./src -Wall -Wextra -Wpedantic -MT src/reactor/reactor_pool.lo -MD -MP -MF src/reactor/.deps/reactor_pool.Tpo -c src/reactor/reactor_pool.c  -fPIC -DPIC -o src/reactor/.libs/reactor_pool.o
src/reactor/reactor_pool.c:16:21: fatal error: dynamic.h: No such file or directory
compilation terminated.
Makefile:1141: recipe for target 'src/reactor/reactor_pool.lo' failed
make[1]: *** [src/reactor/reactor_pool.lo] Error 1
make[1]: Leaving directory '/mnt/ssd/libreactor/libreactor-master'
Makefile:1511: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
root@ip-10-0-0-94:/mnt/ssd/libreactor/libreactor-master#

**Comment by fredrikwidlund** [comment]
Please install https://github.com/fredrikwidlund/libdynamic

**Comment by salesiss** [comment]
Worked, thanks!
