### ISSUE TITLE
Release 2.0 does not build

### ISSUE THREAD

**Issue by RutenkolkC** [fredrikwidlund/libreactor#11]
Hello, I wanted to try out the release 2.0 alpha of libreactor but I cannot get it to compile.

I followed the steps from the `Readme` but the Docker Image does not build.

In `(cd libdynamic-2.3.0/ && ./configure && make install)` the `./configure` does not succeed.

I split the command into parts in the dockerfile to troubleshoot, so my error message may not be exactly the one, one might get after cloning the repo:

```
config.status: error: in `/':
config.status: error: Something went wrong bootstrapping makefile fragments
    for automatic dependency tracking.  If GNU make was not used, consider
    re-running the configure script with MAKE="gmake" (or whatever is
    necessary).  You can also try re-running configure with the
    '--disable-dependency-tracking' option to at least be able to build
    the package (albeit without support for automatic dependency tracking).
See `config.log' for more details
The command '/bin/sh -c libdynamic-2.3.0/configure' returned a non-zero code: 1
make: *** [Makefile:1911: hello] Error 1
```

I started a container from the already built layers and looked at the config, and I believe this may be the source of the failure:

```config.status:1065: creating Makefile
config.status:1065: creating docs/Makefile
config.status:1065: creating examples/Makefile
config.status:1065: creating libdynamic.pc
config.status:1237: executing depfiles commands
config.status:1312: cd .       && sed -e '/# am--include-marker/d' Makefile         | make -f - am--depfiles
make: ./autotools/install-sh: Operation not permitted
make: *** [/tmp/GmfACmif:1139: src/dynamic/.deps/buffer.Plo] Error 127
config.status:1319: $? = 2
config.status:1312: cd examples       && sed -e '/# am--include-marker/d' Makefile         | make -f - am--depfiles
make: .././autotools/install-sh: Operation not permitted
make: *** [/tmp/GmHGdpKK:436: .deps/async.Po] Error 127
config.status:1319: $? = 2
config.status:1323: error: in `/libdynamic-2.3.0':
config.status:1325: error: Something went wrong bootstrapping makefile fragments
    for automatic dependency tracking.  If GNU make was not used, consider
    re-running the configure script with MAKE="gmake" (or whatever is
    necessary).  You can also try re-running configure with the
    '--disable-dependency-tracking' option to at least be able to build
    the package (albeit without support for automatic dependency tracking).
See `config.log' for more details

```

I don't know if this is more a problem with libdynamic, but since the build instructions don't run through right now, I wanted to post this issue here.

**Comment by fredrikwidlund** [comment]
If you try this
```
wget https://github.com/fredrikwidlund/libreactor/releases/download/v2.0.0-alpha/libreactor-2.0.0.tar.gz
tar fvxz libreactor-2.0.0.tar.gz 
cd libreactor-2.0.0
./configure
make hello
```
What happens?

**Comment by RutenkolkC** [comment]
I get the same error.

```
config.status: error: in `/libdynamic-2.3.0':
config.status: error: Something went wrong bootstrapping makefile fragments                         
    for automatic dependency tracking.  If GNU make was not used, consider                          
    re-running the configure script with MAKE="gmake" (or whatever is                               
    necessary).  You can also try re-running configure with the                                     
    '--disable-dependency-tracking' option to at least be able to build                             
    the package (albeit without support for automatic dependency tracking).                         
See `config.log' for more details                                                                   
The command '/bin/sh -c wget https://github.com/fredrikwidlund/libdynamic/releases/download/v2.3.0/libdynamic-2.3.0.tar.gz &&     tar fvxz libdynamic-2.3.0.tar.gz &&     (cd libdynamic-2.3.0/ && ./configure && make install)' returned a non-zero code: 1
```

![build](https://user-images.githubusercontent.com/27628243/108135145-e1875180-70b7-11eb-90fa-55e05491827f.gif)

**Comment by fredrikwidlund** [comment]
It seems to be a build system problem perhaps somehow related to your machine. Could you post the config.log?

**Comment by RutenkolkC** [comment]
sure, but its weird, since the error happens inside building the docker image, which should be absolutely platform independent, right?

But, yeah here is my local `config.log` if it helps:
[config.log](https://github.com/fredrikwidlund/libreactor/files/5999260/config.log)

and I started a container from the last built layer and executed the RUN command and copied the `config.log` from the docker container:
[config.log](https://github.com/fredrikwidlund/libreactor/files/5999291/config.log)

**Comment by fredrikwidlund** [comment]
It is somewhat strange which is why I am saying "perhaps".

In your build you get errors like the following using make
```
configure:3489: make -f confmf.GNU && cat confinc.out
make: /bin/sh: Operation not permitted
make: *** [confinc.mk:2: am__doit] Error 127
```

In an EC2 instance, using the same Dockerfile, for example, I get the following
```
/libdynamic-2.3.0 # grep -A1 make config.log 
running configure, to aid debugging if configure makes a mistake.

--
configure:3269: checking whether make sets $(MAKE)
configure:3292: result: yes
configure:3322: checking whether make supports nested variables
configure:3340: result: yes
configure:3474: checking whether make supports the include directive
configure:3489: make -f confmf.GNU && cat confinc.out
this is the am__doit target
--
config.status:1312: cd .       && sed -e '/# am--include-marker/d' Makefile         | make -f - am--depfiles
config.status:1319: $? = 0
config.status:1312: cd examples       && sed -e '/# am--include-marker/d' Makefile         | make -f - am--depfiles
config.status:1319: $? = 0
--
ac_cv_prog_make_make_set='yes'
am_cv_CC_dependencies_compiler_type='gcc3'
--
am_cv_make_support_nested_variables='yes'
am_cv_prog_cc_c_o='yes'
--
AUTOMAKE='${SHELL} '\''/libdynamic-2.3.0/autotools/missing'\'' automake-1.16'
AWK='awk'
--
MAKEINFO='${SHELL} '\''/libdynamic-2.3.0/autotools/missing'\'' makeinfo'
MANIFEST_TOOL=':'
```

Do you have any custom docker settings? Could you try on another machine, ec2 instance or similar, with a default docker installation, to see if it works for you there?

**Comment by fredrikwidlund** [comment]
https://wiki.alpinelinux.org/wiki/Draft_Release_Notes_for_Alpine_3.14.0#faccessat2

I.e. "Therefore, Alpine Linux 3.14.0 officially requires the host Docker to be version 20.10.0 (which contains moby commit a181391) or greater and the host libseccomp to be version 2.4.4 (which contains backported libseccomp commit 5696c89) or greater"

**Comment by RutenkolkC** [comment]
Oh wow. That might actually be it! My docker version is certainly older.

Will try that later today. Thanks for finding that!

**Comment by RutenkolkC** [comment]
unfortunately, this wasnt it.

I did a fresh install of docker
```
wiredaemon@wiredaemon-desktop:~/libreactor-2.0.0$ docker --version
Docker version 20.10.3, build 48d30b5
``` 

And deleted the folder and did everything from the start (even `docker system prune`d to be sure) but the error still comes up.

**Comment by fredrikwidlund** [comment]
I would recommend updating libseccomp as well and rebooting the system. I do believe this should be the underlying issue.

**Comment by RutenkolkC** [comment]
Alright, I rebooted and the error was still there,

Since the packages for ubuntu 20.04 did not contain a new version of libseccomp, I built and installed it from source, `docker system prune`d, rebooted, extracted the tarball again, tried to `make hello` and the error still comes up.

**Comment by fredrikwidlund** [comment]
Ok, strange. It corresponds exactly with the issue mentioned by Alpine. Try switching to latest instead of edge?

**Comment by RutenkolkC** [comment]
Yes, can confirm that `alpine:latest` works on ubuntu. :tada:  

Thanks alot! I'm very sorry to have bothered you with this. What a weird issue.

Seems like the ubuntu-people are already aware of this problem and working on it. 

https://bugs.launchpad.net/ubuntu/+source/libseccomp/+bug/1914939

**Comment by fredrikwidlund** [comment]
No worries! Hope you enjoy playing around with ilbreactor. :)

**Comment by fredrikwidlund** [comment]
Btw, if you want an example of how to build an app with libreactor, checkout https://github.com/fredrikwidlund/pounce.
