### ISSUE TITLE
link: recipe for target 'example/pool' failed - ubuntu 16.04

### ISSUE THREAD

**Issue by salesiss** [fredrikwidlund/libreactor#2]
linking examples, hello, http, lookup, etc resulted some errors during make,
on ubuntu 16.04:

root@ip-10-0-0-94:/mnt/ssd/libreactor/libreactor-master# make
make[1]: Entering directory '/mnt/ssd/libreactor/libreactor-master'
/bin/bash ./libtool  --tag=CC   --mode=link gcc -std=gnu11 -g -O3 -flto -fuse-linker-plugin -I./src -Wall -Wextra -Wpedantic -lreactor -ldynamic  -o example/pool example/pool.o
libtool: link: gcc -std=gnu11 -g -O3 -flto -fuse-linker-plugin -I./src -Wall -Wextra -Wpedantic -o example/pool example/pool.o  /mnt/ssd/libreactor/libreactor-master/.libs/libreactor.a -ldynamic
/tmp/cc1yirB8.ltrans0.ltrans.o: In function `main':
/mnt/ssd/libreactor/libreactor-master/example/pool.c:35: undefined reference to `reactor_core_construct'
/mnt/ssd/libreactor/libreactor-master/example/pool.c:36: undefined reference to `reactor_pool_construct'
/mnt/ssd/libreactor/libreactor-master/example/pool.c:38: undefined reference to `reactor_pool_enqueue'
/mnt/ssd/libreactor/libreactor-master/example/pool.c:39: undefined reference to `reactor_core_run'
/mnt/ssd/libreactor/libreactor-master/example/pool.c:40: undefined reference to `reactor_pool_destruct'
/mnt/ssd/libreactor/libreactor-master/example/pool.c:41: undefined reference to `reactor_core_destruct'
collect2: error: ld returned 1 exit status
Makefile:1020: recipe for target 'example/pool' failed
make[1]: *** [example/pool] Error 1
make[1]: Leaving directory '/mnt/ssd/libreactor/libreactor-master'
Makefile:1511: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
root@ip-10-0-0-94:/mnt/ssd/libreactor/libreactor-master#

gcc is 5.4: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
salut!

**Comment by fredrikwidlund** [comment]
Please install https://github.com/fredrikwidlund/libdynamic
