### ISSUE TITLE
Please add (optional) REUSEPORT_CBPF support to the release-2.0 branch

### ISSUE THREAD

**Issue by talawahtech** [fredrikwidlund/libreactor#9]
I had previously tried using the [bpf branch](https://github.com/fredrikwidlund/libreactor/tree/bpf), and was only seeing a 2% performance improvement with BPF enabled. Subsequent to that I realized that in order to efficiently use SO_ATTACH_REUSEPORT_CBPF, you must deterministically control the order in which processes are a launched and sockets are opened. Once I did that I saw a 30% increase in throughput, and a 40% drop in p99 latency on my (hyper-optimized) tests (c5n.4xlarge client, c5n.xlarge server).

The [standard BPF program](https://github.com/fredrikwidlund/libreactor/blob/1a4dc120970115d019eedab48fa0fd93983a4c13/src/reactor/reactor_net.c#L53) used with SO_ATTACH_REUSEPORT_CBPF automatically assigns a packet to a given socket based on the core id of the CPU that initially received the packet and did the IRQ processing, CPU 0 -> socket 0. The idea is that if the packet is passed to the userland code running on the same CPU then things are more efficient. However, contrary to my initial assumption, there isn't an automatic mapping between the id of a socket, and the id of the CPU that the userland process (which opened the socket) is running on. The "id" of the socket is determined by the **order** in which sockets are opened. So it works best if the order in which the sockets are opened is controlled to match the order in which processes are pinned to CPUs. 

Previously, I had a for loop that, for each available CPU, (a) forked a child process, (b) pinned it to a CPU, (c) started up an instance of the libreactor server. However since fork() was being called inside a loop, the order in which the sockets actually got opened in the child processes was not deterministic. In some cases the process that was pinned to CPU 0 would actually end up being the third process to open a socket, so it would end up getting packets that had been received on the kernel side by CPU 2 e.g. CPU 2 (kernel) -> socket 2 -> CPU 0 (userland), which of course doesn't bring any efficiency gains.

To resolve this, I used an eventfd semaphore to communicate between the parent and child processes and ensure that the forking happened sequentially, and the order of the sockets being opened matched the order of the CPUs being pinned. Now I am seeing a much more significant performance improvement, so I am eager to see this BPF code added to the release-2.0 branch (which I am using for my tests).

I suspect you are still pretty busy, so please let me know if you would like me to get the ball rolling by creating a PR for you to review. I was thinking this could be an optional flag passed to server_open().

**Comment by talawahtech** [comment]
I just created the PR for this: #10. Let me know if there is anything you would like changed. I mimicked the code from reactor_net.c/h for setting options.

Hoping this can at least be merged into the release-2.0 branch since it is already a fairly experimental branch and not an official release. I am in the process of writing up my blog post about performance tuning on AWS EC2 (using libreactor as the server) and I was hoping to base it on a branch of the official project rather than a fork.

**Comment by fredrikwidlund** [comment]
Added through net_server_filter(), example in example/server.c.

**Comment by fredrikwidlund** [comment]
If you feel like trying out https://github.com/fredrikwidlund/pounce as a comparison to wrk that would be interesting to get feedback on.

**Comment by talawahtech** [comment]
@fredrikwidlund very interesting. I'll try it out when I get a chance.

**Comment by talawahtech** [comment]
@fredrikwidlund I have only done a brief test so far, but I can confirm that pounce was 20-25% faster than wrk in my tests.

Btw I am wrapping up my long overdue blog post about low level performance tuning on EC2. I use libreactor as the server implementation and the results are quite impressive. I will post a link here when the post goes live. Hopefully in the next day or two.

**Comment by talawahtech** [comment]
The post is now live: https://talawah.io/blog/extreme-http-performance-tuning-one-point-two-million/

Thanks again for creating libreator! I don't think there is anything else out there that would have worked as well for this little project.

**Comment by fredrikwidlund** [comment]
@talawahtech Impressive post, I've only looked at it quickly, but I will definitely read it through in detail. Good work!

**Comment by fredrikwidlund** [comment]
@talawahtech Ok, reading it a bit more a have some feedback, however not all of it is positive.

You give yourself a lot of credit for achieving a good end result, which in part is fair but perhaps not completely. You start off with painting a picture of libreactor performing fairly "right up there with" nginx etc, which serves the purpose of the article but I believe is misleading.

* libreactor is not a candidate in the somewhat cripped techempower benchmark, libreactor is production software serving millions of unique end users every day for the last 6 years
* "r18" is left unmaintained for years since the benchmark itself reached a performance ceiling and stopped being meaningful
* The code used is old and does not reflect where libreactor is today
* Using optimizations in libreactor was not invented in this project, it has been using well thought out optimizations since the start, you just worked with a commit with a debug mistake in it, as well you know
* ... and perhaps one or two additional comments

But except for that good work, and a solid and ambitious write up!
